[project]
name = "vitaldb"
version = "1.5.3"
description = "VitalDB Python Libray"
requires-python = ">=3.0"
license = "MIT"
authors = [{name = "VitalLab", email = "vital@snu.ac.kr"}]
dependencies = ['numpy', 'pandas', 'requests', 'wfdb']
